INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer, level, challenge_id) VALUES
('What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 'C', 'Easy'),
('What is 2 + 2?', '3', '4', '5', '6', 'B', 'Easy'),
('Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B', 'Easy'),
('What is the largest ocean on Earth?', 'Atlantic', 'Indian', 'Pacific', 'Arctic', 'C', 'Easy'),
('How many continents are there?', '5', '6', '7', '8', 'C', 'Easy'),
('What is the chemical symbol for water?', 'H2O', 'CO2', 'O2', 'NaCl', 'A', 'Easy'),
('Which animal is known as the king of the jungle?', 'Tiger', 'Lion', 'Elephant', 'Bear', 'B', 'Easy'),
('What color do you get when you mix blue and yellow?', 'Green', 'Purple', 'Orange', 'Brown', 'A', 'Easy'),
('How many days are in a week?', '5', '6', '7', '8', 'C', 'Easy'),
('What is the opposite of hot?', 'Cold', 'Warm', 'Cool', 'Freezing', 'A', 'Easy'),

('What year did World War II end?', '1943', '1944', '1945', '1946', 'C', 'Medium'),
('Who painted the Mona Lisa?', 'Van Gogh', 'Picasso', 'Da Vinci', 'Michelangelo', 'C', 'Medium'),
('What is the currency of Japan?', 'Yuan', 'Won', 'Yen', 'Ringgit', 'C', 'Medium'),
('Which element has the atomic number 6?', 'Oxygen', 'Carbon', 'Nitrogen', 'Hydrogen', 'B', 'Medium'),
('What is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B', 'Medium'),
('Who discovered penicillin?', 'Pasteur', 'Fleming', 'Curie', 'Darwin', 'B', 'Medium',),
('What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C', 'Medium'),
('Which planet has the most moons?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B', 'Medium'),
('What year did the Titanic sink?', '1910', '1911', '1912', '1913', 'C', 'Medium'),
('Who wrote "Romeo and Juliet"?', 'Dickens', 'Hemingway', 'Shakespeare', 'Twain', 'C', 'Medium'),
('What is the largest mammal?', 'Elephant', 'Blue Whale', 'Giraffe', 'Hippo', 'B', 'Medium'),
('Which country invented paper?', 'Egypt', 'India', 'China', 'Greece', 'C', 'Medium'),
('What is the hardest natural substance?', 'Gold', 'Iron', 'Diamond', 'Platinum', 'C', 'Medium'),
('Who was the first person to walk on the moon?', 'Glenn', 'Armstrong', 'Aldrin', 'Collins', 'B', 'Medium'),
('What is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 'B', 'Medium'),
('Which gas do plants absorb from the atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'C', 'Medium'),
('What is the capital of Brazil?', 'Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador', 'C', 'Medium'),
('Who developed the theory of relativity?', 'Newton', 'Einstein', 'Galileo', 'Tesla', 'B', 'Medium'),
('What is the largest desert in the world?', 'Sahara', 'Gobi', 'Arabian', 'Antarctic', 'D', 'Medium'),
('Which organ pumps blood throughout the body?', 'Lungs', 'Liver', 'Heart', 'Brain', 'C', 'Medium'),

('What is the molecular formula of glucose?', 'C6H12O6', 'C12H22O11', 'CH3OH', 'C2H5OH', 'A', 'Hard'),
('Who was the first female Nobel Prize winner?', 'Curie', 'Meitner', 'Franklin', 'Hodgkin', 'A', 'Hard'),
('What year did the Berlin Wall fall?', '1987', '1988', '1989', '1990', 'C', 'Hard'),
('What is the speed of light in km/s?', '299,792', '300,000', '299,000', '301,000', 'A', 'Hard'),
('Which philosopher wrote "The Republic"?', 'Aristotle', 'Socrates', 'Plato', 'Sophocles', 'C', 'Hard'),
('What is the most abundant element in the universe?', 'Oxygen', 'Carbon', 'Hydrogen', 'Helium', 'C', 'Hard'),
('Who composed "The Four Seasons"?', 'Bach', 'Mozart', 'Vivaldi', 'Beethoven', 'C', 'Hard'),
('What is the capital of Kazakhstan?', 'Almaty', 'Astana', 'Nur-Sultan', 'Tashkent', 'B', 'Hard'),
('Which war ended the feudal system in Japan?', 'Sino-Japanese War', 'Boshin War', 'Russo-Japanese War', 'World War II', 'B', 'Hard'),
('What is the pH of pure water?', '5', '6', '7', '8', 'C', 'Hard'),
('Who discovered the electron?', 'Thomson', 'Rutherford', 'Bohr', 'Dalton', 'A', 'Hard'),
('What is the largest bone in the human body?', 'Skull', 'Femur', 'Humerus', 'Tibia', 'B', 'Hard'),
('Which year did the French Revolution begin?', '1776', '1789', '1799', '1804', 'B', 'Hard'),
('What is the chemical symbol for gold?', 'Go', 'Gd', 'Au', 'Ag', 'C', 'Hard'),
('Who wrote "Crime and Punishment"?', 'Tolstoy', 'Dostoevsky', 'Chekhov', 'Pushkin', 'B', 'Hard'),
('What is the deepest ocean trench?', 'Puerto Rico', 'Mariana', 'Java', 'Philippine', 'B', 'Hard'),
('Which country has the most time zones?', 'Russia', 'USA', 'China', 'France', 'A', 'Hard'),
('What is the boiling point of water in Kelvin?', '273K', '313K', '373K', '423K', 'C', 'Hard'),
('Who was the first Emperor of Rome?', 'Julius Caesar', 'Augustus', 'Nero', 'Caligula', 'B', 'Hard'),
('What is the most spoken language in the world?', 'English', 'Spanish', 'Mandarin Chinese', 'Hindi', 'C', 'Hard'),
('Which element has the highest melting point?', 'Iron', 'Tungsten', 'Platinum', 'Titanium', 'B', 'Hard'),
('What year did the Soviet Union collapse?', '1989', '1990', '1991', '1992', 'C', 'Hard'),
('Who painted "The Starry Night"?', 'Monet', 'Renoir', 'Van Gogh', 'Degas', 'C', 'Hard'),
('What is the capital of Myanmar?', 'Yangon', 'Mandalay', 'Naypyidaw', 'Bago', 'C', 'Hard'),
('Which treaty ended World War I?', 'Versailles', 'Paris', 'Vienna', 'Trianon', 'A', 'Hard'),
('What is the rarest blood type?', 'A+', 'B+', 'AB-', 'O-', 'C', 'Hard'),
('Who discovered the structure of DNA?', 'Watson and Crick', 'Franklin', 'Mendel', 'Darwin', 'A', 'Hard'),
('What is the largest island in the world?', 'Borneo', 'Madagascar', 'Greenland', 'New Guinea', 'C', 'Hard'),
('Which year did the first iPhone release?', '2005', '2006', '2007', '2008', 'C', 'Hard'),
('What is the currency of Switzerland?', 'Euro', 'Pound', 'Franc', 'Mark', 'C', 'Hard');
