INSERT INTO activities (name, description, category, difficulty, challenge_id) VALUES
('Basic Greetings', 'Learn hello, goodbye, and basic introductions', 'Language', 'Easy', 9),
('Numbers 1-20', 'Count from one to twenty in English', 'Language', 'Easy', 9),
('Simple Present Tense', 'Practice I am, you are, he is', 'Language', 'Medium', 9),
('Daily Vocabulary', 'Common words for food, places, actions', 'Language', 'Medium', 9),
('Past Tense Verbs', 'Regular and irregular verb forms', 'Language', 'Hard', 9),
('Writing Short Paragraphs', 'Write 5 sentences about yourself', 'Language', 'Hard', 9),
('Bonjour & Au Revoir', 'French greetings and farewells', 'Language', 'Easy', 10),
('Je m appelle', 'Introduce yourself in French', 'Language', 'Easy', 10),
('Ordering at a Cafe', 'Practice food and drink vocabulary', 'Language', 'Medium', 10),
('Asking for Directions', 'Navigate a French city', 'Language', 'Medium', 10),
('Subjunctive Mood', 'Advanced grammar: il faut que, je veux que', 'Language', 'Hard', 10),
('French Debate', 'Express opinions on a topic', 'Language', 'Hard', 10),
('Colors & Numbers', 'Basic Spanish vocabulary', 'Language', 'Easy', 11),
('Family Members', 'Learn family vocabulary', 'Language', 'Easy', 11),
('Food & Restaurant', 'Order meals in Spanish', 'Language', 'Medium', 11),
('Travel Phrases', 'Airport, hotel, directions', 'Language', 'Medium', 11),
('Subjunctive Triggers', 'WEIRDO rules practice', 'Language', 'Hard', 11),
('Spanish Essay', 'Write 200 words in Spanish', 'Language', 'Hard', 11),
('Der Die Das', 'Noun gender basics', 'Language', 'Easy', 12),
('Present Tense Verbs', 'Regular verb conjugation', 'Language', 'Easy', 12),
('Cases Nominative Accusative', 'Subject and direct object', 'Language', 'Medium', 12),
('Modal Verbs', 'Konnen, mussen, wollen, sollen', 'Language', 'Medium', 12),
('Genitive Case', 'Possession and prepositions', 'Language', 'Hard', 12),
('Passive Voice', 'Werden + Partizip II', 'Language', 'Hard', 12),
('Email Basics', 'Professional email structure', 'Language', 'Easy', 13),
('Phone Etiquette', 'Answering and making calls', 'Language', 'Easy', 13),
('Meeting Vocabulary', 'Agenda, minutes, action items', 'Language', 'Medium', 13),
('Negotiation Phrases', 'Making offers and counteroffers', 'Language', 'Medium', 13),
('Presentation Skills', 'Structure and deliver a talk', 'Language', 'Hard', 13),
('Business Report', 'Write a formal report', 'Language', 'Hard', 13),
('Merhaba & Tesekkurler', 'Greetings and thanks', 'Language', 'Easy', 14),
('Numbers & Money', 'Counting and prices', 'Language', 'Easy', 14),
('Restaurant Ordering', 'Food vocabulary and phrases', 'Language', 'Medium', 14),
('Transportation', 'Bus, taxi, directions', 'Language', 'Medium', 14),
('Vowel Harmony', 'Turkish grammar rule', 'Language', 'Hard', 14),
('Conversation Practice', 'Full dialogue simulation', 'Language', 'Hard', 14),
('Italian Sounds', 'Pronunciation basics', 'Language', 'Easy', 15),
('Slow Dialogues', 'Listen and repeat', 'Language', 'Easy', 15),
('News Headlines', 'Comprehend simple news', 'Language', 'Medium', 15),
('Podcast Snippets', 'Understand native speakers', 'Language', 'Medium', 15),
('Movie Scenes', 'Watch without subtitles', 'Language', 'Hard', 15),
('Dictation Exercise', 'Write what you hear', 'Language', 'Hard', 15),
('Thesis Statements', 'Craft strong arguments', 'Language', 'Easy', 16),
('Paragraph Structure', 'Topic sentence, support, conclusion', 'Language', 'Easy', 16),
('Essay Types', 'Compare, argue, analyze', 'Language', 'Medium', 16),
('Citation Styles', 'APA, MLA, Chicago basics', 'Language', 'Medium', 16),
('Academic Voice', 'Formal tone and hedging', 'Language', 'Hard', 16),
('Research Paper', 'Write 1500-word paper', 'Language', 'Hard', 16);